# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy the source code
COPY . .

# Build the project
RUN npm run build

# Expose any necessary port (if needed, but MCP uses stdio, so not needed)

# Run the MCP server
CMD ["node", "build/index.js"]
